#!/bin/bash
# eggd_samsorter_training 0.0.1
# Generated by dx-app-wizard.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

set -exo

main() {

    echo "Value of input_file: '$input_file'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    #download appropriate input files
    dx download "$input_file" -o input_file

    #carry out samtools sorting
    samtools sort -o output_file input_file

    #uploading output file
    output_file=$(dx upload output_file --brief)

    dx-jobutil-add-output output_file "$output_file" --class=file


}
