#!/bin/bash
# Generated by dx-app-wizard.
#
# See https://documentation.dnanexus.com/developer for tutorials on how
# to modify this file.

set -exo

main() {

    echo "Value of input_file: '$bam_file'"

    # The following line(s) use the dx command-line tool to download your file
    # inputs to the local file system using variable names for the filenames. To
    # recover the original filenames, you can use the output of "dx describe
    # "$variable" --name".

    #download appropriate input files
    dx download "$bam_file" -o sample.bam

    #carry out samtools sorting
    samtools sort -o sample_sorted.bam sample.bam

    #uploading output file
    #output_file=$(dx upload output_file --brief)
    outfile=$(dx upload sample_sorted.bam --brief)

    dx-jobutil-add-output sorted_bam_file "$outfile" --class=file
}
